# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://localhost:4000/"

base-img-url: "http://localhost:4000/public/img/"

# Build settings
markdown: kramdown
permalink: pretty


sass:
    sass_dir: /public/_bower_components/bootstrap-sass-official/vendor/assets/stylesheets/

collections:
  offres:
    output: true
    flux: ['Emploi', 'Formation', 'Alternance', 'Flux-4', 'Flux-5']
  articles:
    output: true
    categories: ['Actualité', 'Agenda', 'Co-working', 'Télé-travail', 'Entreprendre']
  maville:
    output: true
    categories: ['Le Mot du Maire', 'Un Territoire Innovant', 'Une Situation Idéale', 'Suivez-nous']
  citoyens:
    output: true
    categories: ['Contacts', 'Annuaire Entreprises', 'Poster une Offre']
  entreprises:
    output: true
    categories: ['Contacts', 'Poster une Offre']